#!/usr/bin/env ruby
# frozen_string_literal: true

script_basename = File.basename(__FILE__)
repo_lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(repo_lib) if File.directory?(repo_lib) && !$LOAD_PATH.include?(repo_lib)

require "kettle/family/version"
if ARGV.any? { |arg| arg == "-v" || arg == "--version" }
  puts Kettle::Family::Version::VERSION
  exit(0)
end

require "kettle/family"

verbose_header = ARGV.delete("--verbose")
puts "== #{script_basename} v#{Kettle::Family::Version::VERSION} ==" if verbose_header && !ARGV.include?("--json")

exit(Kettle::Family::CLI.call(ARGV))
